<h1 style="color: blue;">Data Merging and Lookup Operations with Pandas</h1>

# Task 1: Data Preparation and Missing Value Handling (30 points)

Tasks:<br>
<br>
Create all three DataFrames<br>
For the students DataFrame:<br>
Display null value count and percentage for each column<br>
Fill missing 'city' values with 'Unknown'<br>
Drop rows where 'name' is missing<br>
Display the cleaned students DataFrame<br>

1.Lets Create all three DataFrames

In [2]:
import pandas as pd

In [3]:
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}
df_students_data = pd.DataFrame(students_data)
df_students_data


,student_id,name,email,city
0,101,Alice,alice@email.com,Mumbai
1,102,Bob,bob@email.com,Delhi
2,103,None,charlie@email.com,Bangalore
3,104,David,None,Mumbai
4,105,Emma,emma@email.com,None
5,106,Frank,frank@email.com,Chennai
6,107,Grace,grace@email.com,Delhi


In [4]:
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}
df_enrollments_data = pd.DataFrame(enrollments_data)
df_enrollments_data


,student_id,course_name,enrollment_date
0,101,Python,2024-01-15
1,102,Data Science,2024-01-20
2,103,Python,2024-02-01
3,105,Machine Learning,2024-02-10
4,108,AI,2024-02-15
5,109,Python,2024-03-01


In [5]:
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}
df_scores_data = pd.DataFrame(scores_data)
df_scores_data

,student_id,exam_score
0,101,85
1,102,92
2,104,78
3,105,88
4,106,95


In [6]:
print(f"The number of missing values in each column is:\n{df_students_data.isnull().sum()}")
print(f"The percentage of missing values in each column is:\n{df_students_data.isnull().sum()/len(df_students_data)*100}")

The number of missing values in each column is:
student_id    0
name          1
email         1
city          1
dtype: int64
The percentage of missing values in each column is:
student_id     0.000000
name          14.285714
email         14.285714
city          14.285714
dtype: float64


In [22]:
modified_students_data = df_students_data.copy()
modified_students_data["city"]=modified_students_data["city"].fillna("Unknown")
print(modified_students_data)

   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com    Unknown
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi


In [30]:
modified_students_data = modified_students_data.dropna(subset="name")
print("=== TASK 1: Data Preparation ===")
print(f"The Original Student DataFrame:\n{modified_students_data}")
print(f"\nNull Value Analysis\n{round(df_students_data.isnull().sum()/len(df_students_data)*100, 2)}")

=== TASK 1: Data Preparation ===
The Original Student DataFrame:
   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi

Null Value Analysis
student_id     0.00
name          14.29
email         14.29
city          14.29
dtype: float64


# Task 2: Multiple Join Operations (40 points)

Perform the following join operations and answer questions:<br>
Inner Join: Merge students and enrollments on student_id<br>
<br>
How many students appear in the result?<br>
Which students from the students table are excluded and why?
Left Join: Merge students and enrollments on student_id<br>
<br>
How many total rows are in the result?<br>
Which students have null values in course_name and why?<br>
Right Join: Merge students and enrollments on student_id<br>
<br>
How many total rows are in the result?<br>
Which student_ids appear in the result but don't have student names?<br>
Full Outer Join: Merge students and enrollments on student_id<br>
<br>
How many total rows are in the result?<br>
Display rows where either student name is null OR course_name is null<br>
Add indicator=True parameter to the outer join and show the distribution of merge sources (_merge column)

Inner Join: Merge students and enrollments on student_id
<br>
How many students appear in the result?<br>
Which students from the students table are excluded and why?


In [ ]:
inner_join = pd.merge(df_students_data, df_enrollments_data, on = 'student_id', how = 'inner')
print(inner_join)


   student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         105   Emma     emma@email.com       None  Machine Learning   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3      2024-02-10  


How many students appear in the inner_join result?<br>
Totally, 4 students appear in the result.<br>
Which students from the students table are excluded and why?<br>
The students with student_id 104,106 and 107 are excluded from the result because they do not have corresponding entries in the enrollments table.


In [10]:
left_join = pd.merge(df_students_data, df_enrollments_data, on = 'student_id', how = 'left')
print(left_join)

   student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         104  David               None     Mumbai               NaN   
4         105   Emma     emma@email.com       None  Machine Learning   
5         106  Frank    frank@email.com    Chennai               NaN   
6         107  Grace    grace@email.com      Delhi               NaN   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3             NaN  
4      2024-02-10  
5             NaN  
6             NaN  


How many total rows are in the left_join result?<br>
Totally 7 rows are in the result.<br>
Which students have null values in course_name and why?
The students  "David", " Frank" and "Grace" are having Null values in course_name because they didn't enrolled in any of the course and also there is no entry in the "enrollments_data" table.

In [32]:
right_join = pd.merge(df_students_data, df_enrollments_data, on = 'student_id', how = 'right')
print(right_join)

   student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         105   Emma     emma@email.com       None  Machine Learning   
4         108    NaN                NaN        NaN                AI   
5         109    NaN                NaN        NaN            Python   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3      2024-02-10  
4      2024-02-15  
5      2024-03-01  


How many total rows are in the right_join result?<br>
There are 6 rows in the result<br>
Which student_ids appear in the result but don't have student names?
The student_ids 103, 108 and 109 doesn't have names because there is no entry about their details in the students_data table.

In [12]:
outer_join = pd.merge(df_students_data, df_enrollments_data, on = 'student_id', how = 'outer')
print(outer_join)

   student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         104  David               None     Mumbai               NaN   
4         105   Emma     emma@email.com       None  Machine Learning   
5         106  Frank    frank@email.com    Chennai               NaN   
6         107  Grace    grace@email.com      Delhi               NaN   
7         108    NaN                NaN        NaN                AI   
8         109    NaN                NaN        NaN            Python   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3             NaN  
4      2024-02-10  
5             NaN  
6             NaN  
7      2024-02-15  
8      2024-03-01  


How many total rows are in the outer_join result?<br>
Ther are totally 9 rows in the result.<br>

Display rows where either student name is null OR course_name is null<br>

In [36]:
df_outer = pd.DataFrame(outer_join)
result = df_outer[df_outer['name'].isna() | df_outer['course_name'].isna()]
print("The rows where either student name is null OR course_name is null:\n", result)

The rows where either student name is null OR course_name is null:
    student_id   name              email       city course_name enrollment_date
2         103   None  charlie@email.com  Bangalore      Python      2024-02-01
3         104  David               None     Mumbai         NaN             NaN
5         106  Frank    frank@email.com    Chennai         NaN             NaN
6         107  Grace    grace@email.com      Delhi         NaN             NaN
7         108    NaN                NaN        NaN          AI      2024-02-15
8         109    NaN                NaN        NaN      Python      2024-03-01


In [13]:
outer_join_withindicator = pd.merge(df_students_data, df_enrollments_data, on = 'student_id', how = 'outer', indicator=True)
print(outer_join_withindicator)

   student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         104  David               None     Mumbai               NaN   
4         105   Emma     emma@email.com       None  Machine Learning   
5         106  Frank    frank@email.com    Chennai               NaN   
6         107  Grace    grace@email.com      Delhi               NaN   
7         108    NaN                NaN        NaN                AI   
8         109    NaN                NaN        NaN            Python   

  enrollment_date      _merge  
0      2024-01-15        both  
1      2024-01-20        both  
2      2024-02-01        both  
3             NaN   left_only  
4      2024-02-10        both  
5             NaN   left_only  
6             NaN   left_only  
7      2024-02-15  righ

In [34]:
print("=== Task 2: Data Merging ===")
print("\nInner Join Result:\n", inner_join)
print("\nStudents with null course_name: [104, 106, 107] - Not in enrollments table")
print("\nLeft Join Result:\n", left_join)
print("Excluded Student Names: [David, Frank, Grace] - Not in enrollments table")
print("\nRight Join Result:\n", right_join)
print("Excluded Student Id's [103, 108, 109] - Not in students table")
print("\nOuter Join Result:\n", outer_join)
print
print("\nOuter Join with Indicator Result:\n", outer_join_withindicator)

=== Task 2: Data Merging ===

Inner Join Result:
    student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         105   Emma     emma@email.com       None  Machine Learning   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3      2024-02-10  

Students with null course_name: [104, 106, 107] - Not in enrollments table

Left Join Result:
    student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         104  David               None     Mumbai               NaN   
4         105   Emma     emma@ema

# Task 3: Lookup Operation and Automation (30 points)


Lookup Operation:<br>
<br>
Create a dictionary mapping student_id to exam_score from the scores DataFrame<br>
Use the .map() function to add exam scores to the students DataFrame<br>
Display students with their scores (showing NaN for students without scores)<br>

In [14]:
lookup_dict = df_scores_data.set_index('student_id')['exam_score'].to_dict()
print(lookup_dict)

{101: 85, 102: 92, 104: 78, 105: 88, 106: 95}


In [15]:
df_students_data_copy = df_students_data.copy()
df_students_data_copy["exam_score"] = df_students_data_copy['student_id'].map(lookup_dict)
print(df_students_data_copy)

   student_id   name              email       city  exam_score
0         101  Alice    alice@email.com     Mumbai        85.0
1         102    Bob      bob@email.com      Delhi        92.0
2         103   None  charlie@email.com  Bangalore         NaN
3         104  David               None     Mumbai        78.0
4         105   Emma     emma@email.com       None        88.0
5         106  Frank    frank@email.com    Chennai        95.0
6         107  Grace    grace@email.com      Delhi         NaN


Performance Comparison:<br>
Implement the same score addition using pd.merge() with a left join <br>

In [16]:
left_join1 = pd.merge(df_students_data, df_scores_data, on = 'student_id', how = 'left')
print(left_join1)

   student_id   name              email       city  exam_score
0         101  Alice    alice@email.com     Mumbai        85.0
1         102    Bob      bob@email.com      Delhi        92.0
2         103   None  charlie@email.com  Bangalore         NaN
3         104  David               None     Mumbai        78.0
4         105   Emma     emma@email.com       None        88.0
5         106  Frank    frank@email.com    Chennai        95.0
6         107  Grace    grace@email.com      Delhi         NaN


Explain why lookup (map) is more efficient than merge for this scenario.<br>
In map() we no need to align indexes or manage duplicate columns and it maps the dictionary directly to the defined Dataframe.<br>
But in merge() we need to build the entire DataFrame which is quite inefficient.

In [17]:
def auto_merge(df1, df2, join_type, key_column):
    if join_type == 'inner':
        merged_df = pd.merge(df1, df2, on=key_column, how='inner')
    elif join_type == 'left':
        merged_df = pd.merge(df1, df2, on=key_column, how='left')
    elif join_type == 'right':
        merged_df = pd.merge(df1, df2, on=key_column, how='right')
    elif join_type == 'outer':
        merged_df = pd.merge(df1, df2, on=key_column, how='outer')
    count = len(merged_df)
    result_dict = {'result_df': merged_df, 'count': count, 'join_type': join_type}
    return result_dict


In [37]:
print("=== TASK 3: Lookup and Automation === \n Lookup Operation Result:\n")
input_join_type = input("Enter the type of join (inner, left, right, outer): ")
result = auto_merge(df_students_data, df_enrollments_data, input_join_type, 'student_id')
print(f"The result of the {input_join_type} join is:\n{result}")

=== TASK 3: Lookup and Automation === 
 Lookup Operation Result:

The result of the inner join is:
{'result_df':    student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         105   Emma     emma@email.com       None  Machine Learning   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3      2024-02-10  , 'count': 4, 'join_type': 'inner'}


In [38]:
input_join_type = input("Enter the type of join (inner, left, right, outer): ")
result = auto_merge(df_students_data, df_enrollments_data, input_join_type, 'student_id')
print(f"The result of the {input_join_type} join is:\n{result}")

The result of the outer join is:
{'result_df':    student_id   name              email       city       course_name  \
0         101  Alice    alice@email.com     Mumbai            Python   
1         102    Bob      bob@email.com      Delhi      Data Science   
2         103   None  charlie@email.com  Bangalore            Python   
3         104  David               None     Mumbai               NaN   
4         105   Emma     emma@email.com       None  Machine Learning   
5         106  Frank    frank@email.com    Chennai               NaN   
6         107  Grace    grace@email.com      Delhi               NaN   
7         108    NaN                NaN        NaN                AI   
8         109    NaN                NaN        NaN            Python   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3             NaN  
4      2024-02-10  
5             NaN  
6             NaN  
7      2024-02-15  
8      2024-03-01  , 'count': 9, 'join_type': 'outer